[build]
  command = "npm install && cd frontend && npm install && npm run build"
  publish = "frontend/dist/frontend/browser"
  functions = "backend/netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["backend/netlify/functions/server/**/*"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render"
  status = 200
  force = true

[dev]
  functions = "backend/netlify/functions"
  port = 8888
  targetPort = 4200