[build]
  command = "npm install && cd frontend && npm install && npm run build"
  publish = "frontend/dist/frontend/browser"
  functions = "backend/netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["backend/netlify/functions/server/**/*", "frontend/dist/frontend/browser/index.html"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render"
  status = 200

[dev]
  functions = "backend/netlify/functions"
  port = 8888
  targetPort = 4200